return {}
-- return {
--   "pmizio/typescript-tools.nvim",
--   dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
--   opts = {
--     on_attach = function(client, bufnr)
--       -- your keymaps and buffer options here
--     end,
--     handlers = {
--       -- custom handlers if needed
--     },
--     settings = {
--       separate_diagnostic_server = false,
--       publish_diagnostic_on = "change",
--       expose_as_code_action = {},
--       tsserver_path = nil,
--       tsserver_plugins = {},
--       tsserver_max_memory = "auto",
--       tsserver_format_options = {},
--       tsserver_file_preferences = {},
--       tsserver_locale = "en",
--       complete_function_calls = true,
--       include_completions_with_insert_text = true,
--       code_lens = "all",
--       disable_member_code_lens = true,
--       jsx_close_tag = {
--         enable = true,
--         filetypes = { "javascriptreact", "typescriptreact" },
--       },
--     },
--   },
-- }
